#!/bin/sh

[ -z $TAG_FILE ] && TAG_FILE="./VERSION"
[ -f $TAG_FILE ] || (echo "file with tag must exist, default is ./VERSION,\n custom file can be set with TAG_FILE" && exit 1)
[ -z $USERNAME ] && (echo "env var USERNAME must be set" && exit 1)
[ -z $PASSWORD ] && (echo "env var PASSWORD must be set" && exit 1)
[ -z $IMAGE_NAME ] && (echo "env var IMAGE_NAME must be set" && exit 1)

version=`cat $TAG_FILE`

docker build -t $USERNAME/$IMAGE_NAME:latest ./

docker tag $USERNAME/$IMAGE_NAME:latest $USERNAME/$IMAGE_NAME:$version

docker login -u $USERNAME -p $PASSWORD

echo "deploying $USERNAME/$IMAGE_NAME:latest"
docker push $USERNAME/$IMAGE_NAME:latest

echo "deploying $USERNAME/$IMAGE_NAME:$version"
docker push $USERNAME/$IMAGE_NAME:$version
